"""empty message

Revision ID: 084dbae768a3
Revises: 3e43c56e8eae
Create Date: 2018-01-15 18:05:46.438214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084dbae768a3'
down_revision = '3e43c56e8eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('user', '_password')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('_password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
