"""empty message

Revision ID: 0cccc063c7da
Revises: 10af30a4b9db
Create Date: 2018-01-29 11:54:55.112656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cccc063c7da'
down_revision = '10af30a4b9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('period', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('date_key', sa.Date(), nullable=True),
    sa.Column('chart_id', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('alert_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_type_id'], ['alert_type.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_key', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['alert_type_id'], ['alert_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_threshold')
    op.drop_table('alert')
    op.drop_table('alert_type')
    # ### end Alembic commands ###
