"""empty message

Revision ID: 1035481b32b4
Revises: f8ee08b6a29e
Create Date: 2018-03-19 11:30:39.974188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1035481b32b4'
down_revision = 'f8ee08b6a29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('dashboard', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard', 'type')
    op.drop_column('dashboard', 'description')
    # ### end Alembic commands ###
