"""empty message

Revision ID: 10af30a4b9db
Revises: d71e9a70664c
Create Date: 2018-01-24 14:45:40.941703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10af30a4b9db'
down_revision = 'd71e9a70664c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('date_key', sa.Date(), nullable=True))
    op.drop_column('dashboard_filtered', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_filtered', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('dashboard', 'date_key')
    # ### end Alembic commands ###
