"""empty message

Revision ID: 19b1c9801bc0
Revises: 8626b7d9bfbc
Create Date: 2018-03-06 11:48:09.054875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b1c9801bc0'
down_revision = '8626b7d9bfbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('structure_id', sa.Integer(), nullable=True))
    op.drop_column('task', 'struture_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('struture_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'structure_id')
    # ### end Alembic commands ###
