"""empty message

Revision ID: 252cf284686e
Revises: 51cf658af385
Create Date: 2018-04-24 17:10:23.257744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '252cf284686e'
down_revision = '51cf658af385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart_insight',
    sa.Column('chart_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('insight', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chart_id')
    )
    op.drop_table('user_log')
    op.add_column('task', sa.Column('chart_id', sa.String(length=128), nullable=True))
    op.drop_column('task', 'entity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'chart_id')
    op.create_table('user_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('args', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('request_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('form', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('cookies', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_log_pkey')
    )
    op.drop_table('chart_insight')
    op.drop_table('chart_comment')
    # ### end Alembic commands ###
