"""empty message

Revision ID: 2bb4b2b6832e
Revises: 1f234590803e
Create Date: 2018-03-13 15:23:17.781249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb4b2b6832e'
down_revision = '1f234590803e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen', sa.Column('screenshot', sa.String(length=128), nullable=True))
    op.drop_column('screen', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen', sa.Column('image', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('screen', 'screenshot')
    # ### end Alembic commands ###
