"""empty message

Revision ID: 34e7c4fd6098
Revises: ccb31fea2e52
Create Date: 2018-01-29 19:56:14.924042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e7c4fd6098'
down_revision = 'ccb31fea2e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity_type', sa.Integer(), nullable=True))
    op.drop_column('task', 'EntityType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('EntityType', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'entity_type')
    # ### end Alembic commands ###
