"""empty message

Revision ID: 51cf658af385
Revises: 95271ca8d60d
Create Date: 2018-04-13 17:11:38.025565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51cf658af385'
down_revision = '95271ca8d60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_log')
    op.add_column('report_template', sa.Column('current_cycle_left', sa.Integer(), nullable=True))
    op.add_column('report_template', sa.Column('frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_template', 'frequency')
    op.drop_column('report_template', 'current_cycle_left')
    op.create_table('user_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('args', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('request_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('form', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('cookies', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_log_pkey')
    )
    # ### end Alembic commands ###
