"""empty message

Revision ID: 5891a4bd26db
Revises: d6ceb8323ba1
Create Date: 2018-04-25 11:45:04.340770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5891a4bd26db'
down_revision = 'd6ceb8323ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('chart_id', sa.String(length=128), nullable=True))
    op.add_column('task', sa.Column('entity1_id', sa.Integer(), nullable=True))
    op.drop_column('task', 'entity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('task', 'entity1_id')
    op.drop_column('task', 'chart_id')
    # ### end Alembic commands ###
