"""empty message

Revision ID: 61ef3bc80a9a
Revises: 1035481b32b4
Create Date: 2018-03-20 09:50:18.153715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61ef3bc80a9a'
down_revision = '1035481b32b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_threshold', sa.Column('activate', sa.Integer(), nullable=True))
    op.add_column('alert_threshold', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('alert_threshold', sa.Column('level', sa.String(length=64), nullable=True))
    op.add_column('alert_threshold', sa.Column('period', sa.Integer(), nullable=True))
    op.add_column('alert_threshold', sa.Column('thresh_diff', sa.Float(), nullable=True))
    op.add_column('alert_threshold', sa.Column('thresh_number', sa.Float(), nullable=True))
    op.add_column('alert_threshold', sa.Column('type', sa.String(length=64), nullable=True))
    op.add_column('alert_threshold', sa.Column('y_metric', sa.String(length=128), nullable=True))
    op.drop_constraint('alert_threshold_alert_type_id_fkey', 'alert_threshold', type_='foreignkey')
    op.drop_column('alert_threshold', 'threshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_threshold', sa.Column('threshold', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('alert_threshold_alert_type_id_fkey', 'alert_threshold', 'alert_type', ['alert_type_id'], ['id'])
    op.drop_column('alert_threshold', 'y_metric')
    op.drop_column('alert_threshold', 'type')
    op.drop_column('alert_threshold', 'thresh_number')
    op.drop_column('alert_threshold', 'thresh_diff')
    op.drop_column('alert_threshold', 'period')
    op.drop_column('alert_threshold', 'level')
    op.drop_column('alert_threshold', 'description')
    op.drop_column('alert_threshold', 'activate')
    # ### end Alembic commands ###
