"""empty message

Revision ID: 70e22e3d704a
Revises: d3971e045adf
Create Date: 2018-03-27 13:36:53.522539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e22e3d704a'
down_revision = 'd3971e045adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_item', sa.Column('charting_data', sa.JSON(), nullable=True))
    op.add_column('collection_item', sa.Column('date_key', sa.Date(), nullable=True))
    op.add_column('collection_item', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('collection_item', sa.Column('table_data', sa.JSON(), nullable=True))
    op.drop_column('collection_item', 'chart_id')
    op.drop_constraint('report_report_template_id_fkey', 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'report_template', ['report_template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key('report_report_template_id_fkey', 'report', 'report_template', ['report_template_id'], ['id'])
    op.add_column('collection_item', sa.Column('chart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('collection_item', 'table_data')
    op.drop_column('collection_item', 'name')
    op.drop_column('collection_item', 'date_key')
    op.drop_column('collection_item', 'charting_data')
    # ### end Alembic commands ###
