"""empty message

Revision ID: 748c3c0f11be
Revises: 7d3f9266a382
Create Date: 2018-01-24 14:28:05.095758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748c3c0f11be'
down_revision = '7d3f9266a382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('site_root', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=31), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_filtered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('filters', sa.String(length=1023), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_filtered')
    op.drop_table('dashboard')
    # ### end Alembic commands ###
