"""empty message

Revision ID: 787b289e8b5d
Revises: 252cf284686e
Create Date: 2018-04-24 17:12:54.853729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787b289e8b5d'
down_revision = '252cf284686e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity_id', sa.String(length=128), nullable=True))
    op.drop_column('task', 'chart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('chart_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('task', 'entity_id')
    # ### end Alembic commands ###
