"""empty message

Revision ID: 8626b7d9bfbc
Revises: 982c68259d3f
Create Date: 2018-03-06 11:30:45.967883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8626b7d9bfbc'
down_revision = '982c68259d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('struture_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'struture_id')
    # ### end Alembic commands ###
