"""empty message

Revision ID: 8e8043211b55
Revises: f9cb25586715
Create Date: 2018-05-11 16:28:45.294527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8043211b55'
down_revision = 'f9cb25586715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
