"""empty message

Revision ID: 8f39ff70e163
Revises: c956c2a187c6
Create Date: 2018-04-25 14:03:45.926749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f39ff70e163'
down_revision = 'c956c2a187c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity', sa.JSON(), nullable=True))
    op.drop_column('task', 'entity_type')
    op.drop_column('task', 'entity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('entity_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'entity')
    # ### end Alembic commands ###
