"""empty message

Revision ID: 95271ca8d60d
Revises: b295de5df52c
Create Date: 2018-04-12 13:55:21.778568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95271ca8d60d'
down_revision = 'b295de5df52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_metric_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date_key', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('report', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'data')
    op.drop_table('entity_metric_value')
    # ### end Alembic commands ###
