"""empty message

Revision ID: a8474bc3f0be
Revises: 9f36184e78d3
Create Date: 2018-02-24 16:13:07.574502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8474bc3f0be'
down_revision = '9f36184e78d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'task', ['task_id'], ['id'])
    op.drop_column('comment', 'entity_id')
    op.drop_column('comment', 'entity_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('entity_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'task_id')
    # ### end Alembic commands ###
