"""empty message

Revision ID: bdc1d77ab167
Revises: bc48474d8ccf
Create Date: 2018-05-15 11:40:51.308267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc1d77ab167'
down_revision = 'bc48474d8ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_template', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_template', 'is_delete')
    # ### end Alembic commands ###
