"""empty message

Revision ID: bfb0f95bc208
Revises: ea2cf89c2726
Create Date: 2018-05-02 16:28:04.565169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb0f95bc208'
down_revision = 'ea2cf89c2726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_insight', sa.Column('is_show_original', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_insight', 'is_show_original')
    # ### end Alembic commands ###
