"""empty message

Revision ID: c1258116bd07
Revises: dce5fa7a62dc
Create Date: 2018-04-04 16:59:12.549440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1258116bd07'
down_revision = 'dce5fa7a62dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_threshold', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_threshold', sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
