"""empty message

Revision ID: c72e67e5b0a0
Revises: 8f39ff70e163
Create Date: 2018-04-25 14:08:58.977701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72e67e5b0a0'
down_revision = '8f39ff70e163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'chart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('chart_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
