"""empty message

Revision ID: c956c2a187c6
Revises: 5891a4bd26db
Create Date: 2018-04-25 11:46:12.222814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c956c2a187c6'
down_revision = '5891a4bd26db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.drop_column('task', 'entity1_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('entity1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task', 'entity_id')
    # ### end Alembic commands ###
