"""empty message

Revision ID: ccb31fea2e52
Revises: ff1cbca8dc7a
Create Date: 2018-01-29 19:50:46.331388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb31fea2e52'
down_revision = 'ff1cbca8dc7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('EntityType', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'EntityType')
    # ### end Alembic commands ###
