"""empty message

Revision ID: cf4a6f7b16cf
Revises: bdc1d77ab167
Create Date: 2018-05-16 19:00:45.791684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4a6f7b16cf'
down_revision = 'bdc1d77ab167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('thumbnail', sa.String(length=256), nullable=True))
    op.add_column('report_template', sa.Column('thumbnail', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_template', 'thumbnail')
    op.drop_column('report', 'thumbnail')
    # ### end Alembic commands ###
