"""empty message

Revision ID: cf6ef64abfee
Revises: c72e67e5b0a0
Create Date: 2018-04-25 15:40:34.266577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6ef64abfee'
down_revision = 'c72e67e5b0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task', sa.Column('new_reply', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_task', 'new_reply')
    # ### end Alembic commands ###
