"""empty message

Revision ID: d3971e045adf
Revises: 6c30392f25ff
Create Date: 2018-03-23 15:01:57.083477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3971e045adf'
down_revision = '6c30392f25ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_found')
    op.add_column('collection', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'state')
    op.create_table('manager_found',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='manager_found_pkey')
    )
    # ### end Alembic commands ###
