"""empty message

Revision ID: d71e9a70664c
Revises: 748c3c0f11be
Create Date: 2018-01-24 14:30:15.221249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71e9a70664c'
down_revision = '748c3c0f11be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dashboard_filtered', 'entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboard_filtered', type_='foreignkey')
    # ### end Alembic commands ###
