"""empty message

Revision ID: ea2cf89c2726
Revises: cf6ef64abfee
Create Date: 2018-04-27 20:19:25.024235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2cf89c2726'
down_revision = 'cf6ef64abfee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_time')
    op.drop_column('user', 'created_time')
    op.drop_table('user_entity')
    # ### end Alembic commands ###
