"""empty message

Revision ID: f9cb25586715
Revises: bfb0f95bc208
Create Date: 2018-05-11 15:34:08.510718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cb25586715'
down_revision = 'bfb0f95bc208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_task', 'status')
    # ### end Alembic commands ###
